version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: echo "building app"
      - run: echo "testing app"
       

  test:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: echo "testing app" 
  
  deploy:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: echo "deployed app" 

workflows:
  do-all-the-things:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test